# Generated by Django 5.1.4 on 2025-05-19 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='rol',
            field=models.CharField(choices=[('cliente', 'Cliente'), ('bodeguero', 'Bodeguero'), ('admin', 'Admin')], max_length=20),
        ),
    ]
