# Generated by Django 5.1.4 on 2025-05-14 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herramientas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herramienta',
            name='imagen',
            field=models.CharField(max_length=200),
        ),
    ]
