# Generated by Django 5.1.4 on 2025-05-17 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('herramientas', '0002_alter_herramienta_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herramienta',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='herramienta',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='herramientas/'),
        ),
    ]
