# Generated by Django 5.1.4 on 2025-05-17 04:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orden',
            old_name='fehca',
            new_name='fecha',
        ),
    ]
